### ISSUE TITLE
No Snap point

### ISSUE THREAD

**Issue by blackbeltbullets** [vbawol/DayZ-Epoch#1595]
Dayz epoch.
im trying to build a bridge so to speak with metal floors, got 8 or 9 in... now the on im standing on (last one built) doest have any node's on it to link up and go green with my floor im building, 
i can go back a few panels and turn snap on and i will get a green connection and have rotated around to the front to add more panels to the bridge... but now my item disapears when i get it close to where i want it. what is even going on!?!?!?

**Comment by Windmolders** [comment]
irrelevant
