### ISSUE TITLE
1.0.6 error during compile

### ISSUE THREAD

**Issue by vbawol** [vbawol/DayZ-Epoch#1644]
File p:\z\addons\dayz_code\Configs\CfgWeapons\Weapon\Rifle\FN_FAL_ANPVS4_DZE.hpp, line 0: /CfgWeapons.FN_FAL_ANPVS4_DZE: Undefined base class 'FN_FAL_ANPVS4'
Config : some input after EndOfFile.
Error 3 while parsing
Error in config p:\z\addons\dayz_code\config.cpp

**Comment by seb3sec** [comment]
See #1631 and #1632

**Comment by RimBlock** [comment]
I have both of these merged in my fork and they seem to be working as expected.

**Comment by vbawol** [comment]
thanks @seb3sec for the pull requests and @RimBlock for the confirmation they work.
