### ISSUE TITLE
this server is running an incorrect version of the server side application. you cannot play on this server. if you are the server admin please contact the dayz epoch staff.

### ISSUE THREAD

**Issue by r0lling** [vbawol/DayZ-Epoch#1661]
I have installed the server 5 times new and each time this error shows up.

I download Server files and client from epochmod.com
Have installed MC Visual C++ 2008 x86 2010 x86 2013 x64

got Version 1.63.125584 (<- something like that) on both Server and client

My server runs on a dedi machine.

this my error logs -> http://pastebin.com/6CjSwdTh and http://pastebin.com/N4r6LEdj seems that the hive isnt connectet. 

Had checked each .dll file and unblock blocked files. i don´t know what i can do anymore.

hope someone can help me.

**Comment by ebaydayz** [comment]
It looks like the MySQL service is not running or it is having trouble connecting to the database. Can you connect to the database with a different application like HeidiSQL / Navicat / MySQL workbench / etc.? If yes, double check your HiveExt.ini file settings are correct.

**Comment by r0lling** [comment]
yeah i can connect via Navicat to the Database


and this is my HiveExt.ini   ----> http://pastebin.com/Zq8kh8fh

**Comment by Windmolders** [comment]
@r0lling Did you solve your issue?

**Comment by r0lling** [comment]
not really, i changed my dedicatet Machine and this solves my Problem, so i don´t know maybe it was the Machine

**Comment by Windmolders** [comment]
Could been a problem with not having the right dll's or something, closing this.
