### ISSUE TITLE
Make professional branch system.

### ISSUE THREAD

**Issue by Windmolders** [vbawol/DayZ-Epoch#1662]
# MASTER:
We use Master branch as a ready branch. Only working stuff is in there. Tested and ready to deploy.

# PRODUCTION:
The branch that currently is deployed. On new releases this will contain the master from that date.

# BETA:
A running branch where everyone can do his tests on. Stuff needs to be tested here before they can be pushed to Master.

# Release Branches:
Like u currently have to get easier to older versions. Gets made when a new production is pushed.

# Dev branches: 
Well named branches with only 1 issue fixed in it. Better to have alot of branches with small fixes than alot of fixes in 1 big branches.

# Branch names

Start with the a letter
* F ( feature)
* B ( bug )
* H ( hotfix )
* ...

Followed by the module name
* BUILDING
* SNAP
* ...

Follwed by the issue nummer if existing

Followed by summary of the issue
* NameInDialog
* AddAFriend

### Example

F-Building-1623-AddSingleCurrencySupport.

## Commits
Add the modulename in the commit at the front, possible link to the issue, and a small explanation

[Building] #1623 Added building guide for branches and commits

**Comment by maca134** [comment]
Pretty sure this abit over the top. Maybe 2-3 branches. Github has a nice tagging system that can indicate certain milestones. You have to remember that not everyone know github inside-out.

**Comment by Windmolders** [comment]
See it more like guidelines. The release branches are not really necesairy. But easier for non git users to find older builds. 

Dev branches get deleted once merged to master.
