### ISSUE TITLE
Quite a few trees can't be cut down on Isla Duala

### ISSUE THREAD

**Issue by Utomnia** [vbawol/DayZ-Epoch#1663]
I'm hosting an Isla Duala Arma 2 Epoch server and a number of the trees can't be cut down. I'm happy to work out the models that need to be added and then submit the code to be merged back into the master.

**Comment by Namindu** [comment]
Get the classname. Theirs a array i think might be in variable.sqf but add them to that array and it will work.

**Comment by Utomnia** [comment]
Yeah it's DZE_trees - I'll submit a pull request, make sure it works locally and then submit it back for merging.

**Comment by Utomnia** [comment]
edits complete and pull request done - can someone let me know roughly when it would be included in a release so I can get our community up and running :-)

Thanks

**Comment by Windmolders** [comment]
Added for next release in 1.0.6

**Comment by Windmolders** [comment]
You can always run it until then in your own variables.sqf ofcourse

**Comment by Utomnia** [comment]
But that means that I can't have signature checking on doesn't it? Can I get a build of the dayz_code.pbo that is signed with the epoch1051 key?

**Comment by Windmolders** [comment]
Include the variables.sqf in your mission file. (This pbo gets downloaded by every client. So they will also have it).

And then change the reference in your init.sqf which is next to the variables.sqf in your mission file.

```sqf
//Load In Compiled Functions
call compile preprocessFileLineNumbers "\z\addons\dayz_code\init\variables.sqf";	
```
to
```sqf
//Load In Compiled Functions
call compile preprocessFileLineNumbers "variables.sqf";	
```

This will not create any signature problems.

**Comment by Windmolders** [comment]
Rebuilding the dayz_code will indede give signature problems until full release.

**Comment by Utomnia** [comment]
ok just tried that - works a treat - thanks for your help.

**Comment by Windmolders** [comment]
Closing the issue.
